"""Builds docs/index.html (GitHub Pages) from bench/suite.json, verdicts.json and results.

Usage: python bench/make_site.py      (needs the webp images already in docs/img/bench)
"""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCH = ROOT / "bench"
DOCS = ROOT / "docs"

suite = json.loads((BENCH / "suite.json").read_text(encoding="utf-8"))
verdicts = json.loads((BENCH / "verdicts.json").read_text(encoding="utf-8"))
qres = json.loads((BENCH / "results/qwen/results.json").read_text(encoding="utf-8"))
gres = json.loads((BENCH / "results/gpt/results.json").read_text(encoding="utf-8"))
credits = {c["file"]: c for c in json.loads((BENCH / "inputs/credits.json").read_text(encoding="utf-8"))}
tiers_dir = BENCH / "tiers/results"

CAT = {"Fotografía": "Photography", "Creatividad": "Creativity", "Edición": "Photo editing"}
WIN = {"qwen": "Qwen wins", "gpt": "gpt-image-2 wins", "tie": "Tie"}
esc = html.escape

tally = {}
for t in suite:
    c = CAT[t["cat"]]
    tally.setdefault(c, {"qwen": 0, "tie": 0, "gpt": 0})
    tally[c][verdicts[t["id"]]["winner"]] += 1
total = {k: sum(v[k] for v in tally.values()) for k in ("qwen", "tie", "gpt")}


def mins(xs):
    return f"{sum(xs) / len(xs) / 60:.1f} min" if xs else "n/a"


q_t2i = [qres[t["id"]]["seconds"] for t in suite if t["mode"] == "t2i"]
q_edit = [qres[t["id"]]["seconds"] for t in suite if t["mode"] == "edit"]
g_all = [gres[t["id"]]["seconds"] for t in suite if t["id"] in gres]

score_rows = "".join(
    f"<tr><th scope=row>{c}</th><td>{v['qwen']}</td><td>{v['tie']}</td><td>{v['gpt']}</td></tr>" for c, v in tally.items()
)

# VRAM tiers table (from bench/tiers/run.sh), if present
tier_rows = ""
TIER_LABEL = {
    "12gb-balanced": "12 GB card · balanced",
    "8gb-compact": "Soft 8 GB cap · compact",
    "8gb-balanced": "Soft 8 GB cap · balanced",
}
TEST_LABEL = {"t2i_draft": "Text→image 1024², 20 steps", "t2i_standard_16x9": "Text→image 1.6 MP, 30 steps", "edit_snow": "Photo edit 1280 px, 30 steps"}
if tiers_dir.exists():
    for tier, label in TIER_LABEL.items():
        p = tiers_dir / tier / "results.json"
        if not p.exists():
            continue
        r = json.loads(p.read_text(encoding="utf-8"))
        for tid, tl in TEST_LABEL.items():
            x = r.get(tid)
            if not x:
                continue
            if "error" in x:
                tier_rows += f"<tr><th scope=row>{label}</th><td>{tl}</td><td colspan=3>failed: {esc(x['error'][:80])}</td></tr>"
            else:
                tier_rows += (
                    f"<tr><th scope=row>{label}</th><td>{tl}</td><td>{x['seconds']:.0f} s</td>"
                    f"<td>{x['secondsPerStep']:.2f}</td><td>{x['peakVramMb'] / 1024:.1f} GB</td></tr>"
                )

cards = []
for t in suite:
    tid = t["id"]
    v = verdicts[tid]
    cells = []
    for f in t.get("images", []):
        c = credits[f]
        stem = Path(f).stem
        cells.append(
            f'<figure class="in"><figcaption><b>Input photo</b><span>{esc(c["author"])} · {esc(c["license"])}</span></figcaption>'
            f'<a href="img/bench/in_{stem}.webp"><img src="img/bench/in_{stem}.webp" loading="lazy" alt="Input photo for {esc(v["title"])} by {esc(c["author"])}"></a></figure>'
        )
    for side, res, lab in (("qwen", qres, "Qwen-Image-2.1 · local RTX 3060"), ("gpt", gres, "gpt-image-2 · cloud")):
        secs = res.get(tid, {}).get("seconds")
        meta = f"{secs / 60:.1f} min" if secs else ""
        cells.append(
            f'<figure class="{side}"><figcaption><b>{lab}</b><span>{meta}</span></figcaption>'
            f'<a href="img/bench/{tid}_{side}.webp"><img src="img/bench/{tid}_{side}.webp" loading="lazy" '
            f'alt="{esc(v["title"])}, generated by {lab.split(" ·")[0]}"></a></figure>'
        )
    cards.append(
        f'<article id="{tid}"><header><p class="k">{CAT[t["cat"]]} · {"edit" if t["mode"] == "edit" else "text-to-image " + t.get("ar", "")}</p>'
        f'<h3>{esc(v["title"])}</h3><span class="w w-{v["winner"]}">{WIN[v["winner"]]}</span></header>'
        f'<details><summary>Prompt</summary><p>{esc(t["prompt"])}</p></details>'
        f'<div class="row">{"".join(cells)}</div><p class="note">{esc(v["note"])}</p></article>'
    )

faq = [
    ("What AI image model runs on a 12 GB GPU?",
     "Qwen-Image-2.1 (7B, open weights, September 2026) runs fully in VRAM on a 12 GB card such as an RTX 3060 when you use the int8 weights and load the text encoder, the image model and the VAE one at a time. qwen-image-local does that for you: about 35 seconds for a 1024×1024 image and about 7 minutes at native 2K."),
    ("Can Qwen-Image-2.1 run on an 8 GB GPU?",
     "Not verified yet. The compact profile swaps the text encoder for a 6.3 GB w4a8 version and cuts peak VRAM by about 2.5 GB at the same speed, so it should fit 10 GB cards. We could only emulate 8 GB with a soft cap, and peak usage still went above 8 GB, so treat 8 GB cards as untested."),
    ("Is Qwen-Image-2.1 as good as gpt-image-2?",
     f"For photo editing, yes in our tests: {tally['Photo editing']['tie']} ties and {tally['Photo editing']['qwen']} win out of 8 edits. For text-to-image, no: gpt-image-2 won {tally['Photography']['gpt'] + tally['Creativity']['gpt']} of 12, mostly on prompt adherence and world knowledge."),
    ("Is it free to use commercially?",
     "The app is MIT. The Qwen-Image-2.1 weights are under the Qwen Research License, which does not allow commercial use without a separate license from Alibaba."),
]
faq_html = "".join(f"<details><summary>{esc(q)}</summary><p>{esc(a)}</p></details>" for q, a in faq)
ld = {
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "SoftwareApplication",
            "name": "qwen-image-local",
            "operatingSystem": "Windows 10, Windows 11",
            "applicationCategory": "MultimediaApplication",
            "description": "Run Qwen-Image-2.1 text-to-image and photo editing fully in VRAM on a 12 GB NVIDIA GPU. Desktop app and CLI.",
            "url": "https://github.com/Mats2208/qwen-image-local",
            "license": "https://opensource.org/licenses/MIT",
            "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
        },
        {
            "@type": "FAQPage",
            "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faq],
        },
    ],
}

page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Qwen-Image-2.1 on a 12 GB GPU vs gpt-image-2 — 20-test benchmark</title>
<meta name="description" content="Qwen-Image-2.1 running locally on an RTX 3060 12 GB, tested against gpt-image-2 on 20 prompts: photography, creativity and editing of real photos. Every image, prompt and timing.">
<link rel="canonical" href="https://mats2208.github.io/qwen-image-local/">
<meta property="og:title" content="Qwen-Image-2.1 on a 12 GB GPU vs gpt-image-2">
<meta property="og:description" content="20 prompts, one run each, every image published. Edits: on par. Text-to-image: gpt-image-2 ahead.">
<meta property="og:image" content="https://raw.githubusercontent.com/Mats2208/qwen-image-local/main/assets/banner.jpg">
<meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">{json.dumps(ld, ensure_ascii=False)}</script>
<style>
:root{{--bg:#f6f6f4;--fg:#121212;--mut:#62625f;--line:#dcdcd8;--card:#fff;--q:#4f46e5;--g:#0f766e;--t:#6b6b62}}
@media (prefers-color-scheme:dark){{:root{{--bg:#101011;--fg:#ececea;--mut:#9b9b98;--line:#2a2a2c;--card:#17171a;--q:#a5a0ff;--g:#4fd1b5;--t:#b4b4aa}}}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--fg);font:15px/1.6 "Segoe UI",system-ui,-apple-system,sans-serif;padding:0 16px 64px}}
main{{max-width:1240px;margin:0 auto}}a{{color:inherit}}
.hero img{{width:100%;display:block;margin:24px 0 0;border-radius:3px}}
h1{{font-size:clamp(26px,4vw,40px);letter-spacing:-.02em;line-height:1.1;margin:28px 0 8px}}h2{{margin:44px 0 12px;font-size:22px}}h3{{margin:0;font-size:17px}}
.lead{{max-width:72ch;color:var(--mut)}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:16px}}
.box{{background:var(--card);border:1px solid var(--line);border-radius:3px;padding:16px}}
table{{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}}th,td{{padding:6px 8px;border-bottom:1px solid var(--line);text-align:right}}th[scope=row],thead th:first-child,td:nth-child(2){{text-align:left}}
thead th{{font:600 12px ui-monospace,Consolas,monospace;text-transform:uppercase;color:var(--mut)}}
.wrap{{overflow-x:auto}}
article{{background:var(--card);border:1px solid var(--line);border-radius:3px;padding:16px;margin:0 0 20px}}
article header{{display:flex;flex-wrap:wrap;gap:8px 12px;align-items:baseline}}.k{{margin:0;width:100%;font:600 11px ui-monospace,Consolas,monospace;text-transform:uppercase;color:var(--mut)}}
.w{{font:600 12px ui-monospace,Consolas,monospace;padding:2px 8px;border-radius:2px;border:1px solid var(--line)}}.w-qwen{{color:var(--q)}}.w-gpt{{color:var(--g)}}.w-tie{{color:var(--t)}}
details{{margin:8px 0}}summary{{cursor:pointer;color:var(--mut);font-size:13px}}details p{{color:var(--mut);font-size:14px;max-width:100ch}}
.row{{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:12px;margin-top:8px}}
figure{{margin:0}}figcaption{{display:flex;justify-content:space-between;gap:8px;font-size:12px;margin-bottom:4px}}figcaption span{{color:var(--mut)}}
figure img{{width:100%;height:auto;display:block;border:1px solid var(--line);border-radius:2px;background:repeating-conic-gradient(#8882 0 25%,#0000 0 50%) 0 0/16px 16px}}
.qwen b{{color:var(--q)}}.gpt b{{color:var(--g)}}.note{{margin:10px 0 0;max-width:100ch}}
code{{font-family:ui-monospace,Consolas,monospace;font-size:13px}}footer{{margin-top:48px;color:var(--mut);font-size:13px}}
</style>
</head>
<body><main>
<div class="hero"><img src="https://raw.githubusercontent.com/Mats2208/qwen-image-local/main/assets/banner.jpg" alt="qwen-image-local banner, generated and then edited by Qwen-Image-2.1 on an RTX 3060"></div>
<h1>Qwen-Image-2.1 on a 12 GB GPU vs gpt-image-2</h1>
<p class="lead">20 prompts, one run per model, no cherry-picking. Qwen-Image-2.1 ran locally on an RTX 3060 12 GB with <a href="https://github.com/Mats2208/qwen-image-local">qwen-image-local</a> (int8 weights, 40 steps, native 2K). gpt-image-2 ran in the cloud through ChatGPT. Edits use real photos from Wikimedia Commons.</p>

<div class="grid">
<div class="box"><h2 style="margin-top:0">Score</h2><div class="wrap"><table>
<thead><tr><th>Category</th><th>Qwen</th><th>Tie</th><th>gpt-image-2</th></tr></thead>
<tbody>{score_rows}</tbody>
<tfoot><tr><th scope=row>Total</th><td>{total['qwen']}</td><td>{total['tie']}</td><td>{total['gpt']}</td></tr></tfoot>
</table></div>
<p class="lead" style="font-size:14px">Short version: <b>for editing photos, Qwen-Image-2.1 is on par with gpt-image-2</b> and it is free, private and unlimited on your own card. For text-to-image it follows long prompts less closely and knows less about the world (it drew a Chinese gourd for "mate" twice).</p></div>
<div class="box"><h2 style="margin-top:0">Time per image</h2><div class="wrap"><table>
<thead><tr><th>Run</th><th>Average</th></tr></thead><tbody>
<tr><th scope=row>Qwen · text→image · native 2K, 40 steps</th><td>{mins(q_t2i)}</td></tr>
<tr><th scope=row>Qwen · edit · 1536 px, 40 steps</th><td>{mins(q_edit)}</td></tr>
<tr><th scope=row>Qwen · text→image · 1024², 20 steps</th><td>0.6 min</td></tr>
<tr><th scope=row>gpt-image-2 · cloud, 3 in parallel</th><td>{mins(g_all)}</td></tr>
</tbody></table></div>
<p class="lead" style="font-size:14px">Peak VRAM during a native 2K generation: 11.9 of 12.0 GB. Each model (text encoder 8.9 GB, image model 6.9 GB, VAE 0.6 GB) is loaded fully into VRAM when its stage runs; nothing is split between CPU and GPU.</p></div>
</div>

{"<h2>VRAM profiles</h2><p class=lead>Same prompts on the 12 GB card, then with ComfyUI told to leave 4.3 GB free (<code>--reserve-vram 4.3</code>). That cap is soft: peak usage (desktop included) still went above 8 GB with both profiles, so <b>this does not prove the app runs on a real 8 GB card</b>. What it does show: the compact profile lowers peak VRAM by about 2.5 GB at the same speed. Reproduce with <code>bash bench/tiers/run.sh</code>.</p><div class='box wrap'><table><thead><tr><th>Setup</th><th>Test</th><th>Total</th><th>s/step</th><th>Peak VRAM</th></tr></thead><tbody>" + tier_rows + "</tbody></table></div>" if tier_rows else ""}

<h2>All 20 tests</h2>
{"".join(cards)}

<h2>FAQ</h2>
<div class="box">{faq_html}</div>

<footer>
<p>Reproduce: <code>qil bench --suite bench/suite.json --preset max</code>. Full-resolution PNGs are attached to the GitHub release. Input photos: Wikimedia Commons, authors and licenses in <a href="https://github.com/Mats2208/qwen-image-local/blob/main/bench/inputs/credits.json">credits.json</a>; edits of CC BY-SA photos are CC BY-SA 4.0.</p>
<p>qwen-image-local is unofficial and not affiliated with Alibaba or the Qwen team. Qwen-Image-2.1 is released under the Qwen Research License (non-commercial).</p>
</footer>
</main></body></html>
"""
(DOCS / "index.html").write_text(page, encoding="utf-8")
print("docs/index.html", len(page) // 1024, "KB ·", len(cards), "tests · score", total)
